# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  dotNetFramework: 'net6.0'
  dotNetVersion: '6.0.x'
  targetRuntime: 'linux-x64'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '$(dotNetVersion)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '$(solution)'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-r $(targetRuntime) --framework $(dotNetFramework) --self-contained -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)'


- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '$(solution)'
